---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: "yes"

- name: install nodejs and npm
  become: true
  apt:
    name: [nodejs, npm]

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
