---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages."
  become: true
  apt:
    upgrade: yes

- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: install nodejs and npm
  become: true
  apt:
    name: [nodejs, npm]

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: create backend directory on EC2
  become: true
  file:
    #path: /home/ubuntu/backend
    path: ~/backend
    state: directory 
    mode: 0755

- name: copy files to backend
  become: true
  copy: 
    src: artifact.tar.gz
    #dest: /home/ubuntu/backend/artifact.tar.gz
    dest: ~/backend/artifact.tar.gz

- name: unzip backend directory
  become: true
  shell: |
    #cd /home/ubuntu/backend
    cd ~/backend
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz

- name: start application
  become: true
  shell: |
    #cd /home/ubuntu/backend
    cd ~/backend
    npm cache clean -f
    npm install -g n
    n stable
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env

- name: print environment variables
  become: true
  shell: |
    printenv
  register: printenv_out

- name: print message
  debug:
      msg: "{{ printenv_out.stdout_lines }}"
